[package]
name = "tanix-net"
version.workspace = true
edition.workspace = true
description = "Tanix Phase-11 network server — socket layer (TCP/UDP) over virtio-net"

[dependencies]
tanix-libsys = { path = "../libtanix-sys" }
tanix-libdrv = { path = "../libtanix-drv" }
tanix-libnet = { path = "../libtanix-net" }